apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service-clusterIP
spec: 
  selector: 
    project: expense 
    module: backend
    environment: dev
  type: ClusterIP
  ports: 
  - protocol: TCP
    port: 80 
    targetport: 80 
  

