apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: nginx-deploy
  labels: 
    app: nginx 
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      app: nginx 
  service: nginx-service-stateful
  template: 
    metadata: 
      name: stateful-pod
      labels: 
        app: nginx 
    spec: 
      containers:
      - name: nginx
        image: nginx
        ports: 
        - containerPort: 80
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service-stateful 
spec: 
  selector: 
    app: nginx 
  clusterIP: None
  ports: 
  - port: 80 
    targetPort: 80