apiVersion: apps/v1
kind: pod
metadata: 
  name: pod 
  labels: 
    environment: dev
    project: expense 
    module: backend 
spec: 
  containers:
  - name: nginx
    image: nginx
    containerPort: 80
    env: 
    - name: course 
      duration: "10"
    - name: trainer
      value: "siva" 
      