apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: expense
  labels: 
    app: frontend
    tier: web
    project: expense 
spec: 
  replicas: 2 
  selector: 
    matchLabels:
      app: frontend
      tier: web
      project: expense 
  template: 
    metadata: 
      labels: 
        app: frontend
        tier: web
        project: expense 
    spec: 
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        resources: 
          requests: 
            cpu: 100m 
            memory: 128Mi  
            # limits are greater than or equl to requests
          limits: 
            cpu: 100m 
            memory: 128Mi
---
apiVersion: v1 
kind: Service 
metadata: 
  name: frontend
  namespace: expense
spec: 
  selector: 
    app: frontend
    tier: web
    project: expense  
  type: LoadBalancer
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
    