FROM almalinux:9 
ENV course="Devops with AWS" \
    trainer="DIVYA" \
    duration="120hrs"
ARG course="devops with aws" \
    duration="120hrs" 
RUN echo "course: $course, duration: $duration"
CMD ["sleep", "100"]
