apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: expense
  labels: 
    app: mysql
    tier: db
    project: expense 
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      app: mysql
      tier: db
      project: expense 
  template: 
    metadata: 
      labels: 
        app: mysql
        tier: db
        project: expense 
    spec: 
      containers:
      - name: mysql
        image: divyavutakanti/mysql:v1

---

apiVersion: v1 
kind: Service 
metadata: 
  name: mysql
  namespace: expense
spec: 
  selector: 
    app: mysql
    tier: db
    project: expense 
  type: ClusterIP
  ports: 
  - port: 3306 
    targetPort: 3306
    protocol: TCP

    