apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-static-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f4ddb5c156eb5bef
  

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: expense-static-pv
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi