apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-expense"
  resources:
    requests:
      storage: 5Gi

--- 
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v hostpath:contaierpath
    - name: efs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-dynamic
    persistentVolumeClaim:
      claimName: efs-dynamic
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007