- name: variables precedence 
  hosts: web 
  vars:
    COURSE: DevOps from play level
  # vars_files:
  # - vars.yaml
  vars_prompt:
  - name: COURSE 
    prompt: Please enter the course name
    private: false
  tasks:
  - name: print variables depends on precedence 
    # vars: 
    #   COURSE: DevOps from task level 
    ansible.builtin.debug:  
      msg: "Hi, Iam learning {{COURSE}}" 

  
