- name: check a number is less than 10 or not 
  hosts: local 
  connection: local 
  # vars_prompt:
  # - name: my_number 
  #   prompt: please enter the number 
  #   private: false
  vars:
   name: "divya"
  tasks: 
  - name: print given number if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than 10"
    when: my_number | int  < 10  #condition expressiion
  - name: print given number is greater than 10 
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is greater than 10"
    when: my_number | int >= 10 
