- name: create a user 
  hosts: web 
  become: yes
  tasks: 
  - name: check user exist or not 
    ansible.builtin.command: id expense 
    register: USER # here USER is varaible that gets output from above command

  - name: print the user information
    ansible.builtin.debug: 
      msg: "user info: {{USER}}"