- name: loops demo 
  hosts: web 
  tasks: 
  - name: print names 
    ansible.builtin.debug: 
      name: "{{ item }}"
      state: present 
    loop:
    - mysql
    - nginx 
    - postfix 
    - httpd