- name: demo on filters/functions
  hosts: web 
  become: yes 
  tasks: 
  - name: print the default variables
    ansible.builtin.debug:
      msg: "Hi , Iam learning {{course | default('Ansible')}}"
  - name: convert to uppercase 
    vars:
      greeting: "Hello ramesh"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"
  
  - name: convert to uppercase 
    vars:
      greeting: "Hello ramesh"
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"
  - name: get the unique values 
    vars: 
      numbers: [1,2,3,4,5,4,3]
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"