- name: demo on filters/functions
  hosts: web 
  become: yes 
  tasks: 
  - name: print the default variables
    ansible.builtin.debug:
      msg: "Hi , Iam learning {{course | default('Ansible')}}"
  - name: convert to uppercase 
    vars:
      greeting: "Hello ramesh"
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"
  
  - name: convert to uppercase 
    vars:
      greeting: "Hello ramesh"
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"
  - name: get the unique values 
    vars: 
      numbers: [1,2,3,4,5,4,3]
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"

  - name: convert map to list
    vars: 
      course:
        name: "Devops with Aws"
        duration: 120
        trainer: "sivakumar"
    ansible.builtin.debug:
      msg: "{{course | dict2items}}"

  - name: convert list  to map
    vars: 
      course:
        - { "key": "name", "value": "Devops with AWS"}
        - { "key": "duration", "value": 120}
        - { "key": "trainer", "value": "sivakumar reddy"}
    ansible.builtin.debug:
      msg: "{{course | item2dict}}"
  - name: check the ip address 
    vars: 
      ip : 54.204.84.161
    ansible.builtin.debug: 
      msg: "{{ip | anisble.utils.ipv4 }}"