- name: create a ec2 insatnce and route53 
  hosts: local 
  connection: local
  vars:
    subnet_id: subnet-0509f144a358e12de
    sg_id: sg-08eed4ca0fd852a9e
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
  tasks: 
  - name: execute the command 
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: {{subnet_id}}
      instance_type: t2.micro
      security_group: {{sg_id}}
      image_id: {{ami_id}}
    loop: {{instances}} 
    register: ec2_instances
