# Label the node: kubectl label nodes ip-192-168-20-125.ec2.internal hardware=gpu 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable-perl
  nodeSelector:
    hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"