apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app2
  labels: 
    name: app2 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: app2
  template: 
    metadata: 
      labels: 
        name: app2 
    spec: 
      containers:
      - name: app2
        image: divyavutakanti/app2:v1
        ports: 
        - containerPort: 80
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: app2
spec: 
  selector: 
    name: app2
  type: ClusterIP
  ports: 
  - port: 80 
    targetPort: 80

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: echoserver
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:461997657539:certificate/4cbebf80-49f9-42d4-a3c9-e4fde4c88984
      alb.ingress.kubernetes.io/listen-ports: '[ {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
      alb.ingress.kubernetes.io/group.name: expense
spec:
    rules:
    - host: "app2.dev.divyavutakanti.com"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: app2
              port:
                number: 80